[package]
name = "ez-stream-module"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
env_logger = "0.11.8"
lazy_static = "1.5.0"
log = "0.4.29"
serde = "1.0.228"
serde-saphyr = "0.0.10"
